version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=telegramdb
      - POSTGRES_USER=telegram_user
      - POSTGRES_PASSWORD=telegram_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
